[package]
name = "simple_utf8"
version = "0.1.0"
authors = ["CNife <CNife@vip.qq.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[dev-dependencies]
lazy_static = "1.4.0"